// actionTypes.js
export const FETCH_ISSUES_REQUEST = 'FETCH_ISSUES_REQUEST';
export const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS';
export const FETCH_ISSUES_FAILURE = 'FETCH_ISSUES_FAILURE';

export const FETCH_ISSUES_BY_ID_REQUEST = 'FETCH_ISSUES_BY_ID_REQUEST';
export const FETCH_ISSUES_BY_ID_SUCCESS = 'FETCH_ISSUES_BY_ID_SUCCESS';
export const FETCH_ISSUES_BY_ID_FAILURE = 'FETCH_ISSUES_BY_ID_FAILURE';

export const CREATE_ISSUE_REQUEST = 'CREATE_ISSUE_REQUEST';
export const CREATE_ISSUE_SUCCESS = 'CREATE_ISSUE_SUCCESS';
export const CREATE_ISSUE_FAILURE = 'CREATE_ISSUE_FAILURE';

export const UPDATE_ISSUE_REQUEST = 'UPDATE_ISSUE_REQUEST';
export const UPDATE_ISSUE_SUCCESS = 'UPDATE_ISSUE_SUCCESS';
export const UPDATE_ISSUE_FAILURE = 'UPDATE_ISSUE_FAILURE';

export const UPDATE_ISSUE_STATUS_REQUEST = 'UPDATE_ISSUE_STATUS_REQUEST';
export const UPDATE_ISSUE_STATUS_SUCCESS = 'UPDATE_ISSUE_STATUS_SUCCESS';
export const UPDATE_ISSUE_STATUS_FAILURE = 'UPDATE_ISSUE_STATUS_FAILURE';

export const DELETE_ISSUE_REQUEST = 'DELETE_ISSUE_REQUEST';
export const DELETE_ISSUE_SUCCESS = 'DELETE_ISSUE_SUCCESS';
export const DELETE_ISSUE_FAILURE = 'DELETE_ISSUE_FAILURE';

export const ASSIGNED_ISSUE_TO_USER_REQUEST = 'ASSIGNED_ISSUE_TO_USER_REQUEST';
export const ASSIGNED_ISSUE_TO_USER_SUCCESS = 'ASSIGNED_ISSUE_TO_USER_SUCCESS';
export const ASSIGNED_ISSUE_TO_USER_FAILURE = 'ASSIGNED_ISSUE_TO_USER_FAILURE';
